<?php declare(strict_types = 1);

namespace Cspray\Labrador\AsyncEvent;

use Amp\Promise;
use Ds\Map;
use Ds\Pair;

/**
 * Represents an object that allows listeners to respond to emitted events using the full async power of amp.
 *
 * This interface is not to be confused with the concept of Amp's Emitter implementation. While similar this API is
 * intended to satisfy different requirements with a more traditional feel for emitting events.
 *
 * @package Cspray\Labrador\AsyncEvent
 */
interface EventEmitter {

    /**
     * Invoke a listener every time an Event with a name matching $event is emitted; any data passed to $listenerData
     * will be passed to the $listener after the Event argument.
     *
     * Each $listener is invoked within the context of a running event loop. The specific signature for an event
     * $listener looks like:
     *
     * function(Event, ...$listenerData) : Promise<void>|Generator|void {}
     *
     * @param string $event
     * @param callable $listener
     * @param array $listenerData
     * @return ListenerId
     */
    public function on(string $event, callable $listener, array $listenerData = []) : ListenerId;

    /**
     * Turns off a listener that is identified by $listenerId.
     *
     * @param ListenerId $listenerId
     * @return void
     */
    public function off(ListenerId $listenerId) : void;

    /**
     * Ensures that a $listener is only executed one time the next time the event is emitted; after the event is
     * emitted this listener will be removed.
     *
     * The specific signature for an event $listener looks like:
     *
     * function(Event, ...$listenerData) : Promise<void>|Generator|void {}
     *
     * Each $listener is invoked within the context of a running event loop.
     *
     * The returned string is an id that can identify this listener for later removal.
     *
     * @param string $event
     * @param callable $listener
     * @param array $listenerData
     * @return ListenerId
     */
    public function once(string $event, callable $listener, array $listenerData = []) : ListenerId;

    /**
     * Causes all registered listeners for $event->name() to be invoked; the Promises generated by registered listeners
     * will be combined using the passed $promiseCombinator or the default PromiseCombinator.
     *
     * This method allows events to be fired in a way that allows calling code to fire-and-forget or "wait" until all
     * listener Promises have resolved according to the PromiseCombinator used. If you need to ensure that all listeners
     * have had a chance to react to the emitted event simply yield the returned Promise (and make sure you're using
     * the correct PromiseCombinator for your use case).
     *
     * Generally speaking you should not rely on values resolved from the returned Promise; they will be dependent on
     * the exact PromiseCombinator used.
     *
     * @param Event $event
     * @param PromiseCombinator|null $promiseCombinator
     * @return Promise<mixed>
     */
    public function emit(Event $event, PromiseCombinator $promiseCombinator = null) : Promise;

    /**
     * Return the number of listeners registered for a specific event.
     *
     * @param string $event
     * @return int
     */
    public function listenerCount(string $event) : int;

    /**
     * Returns a Map of lister information for a given $event.
     *
     * The key for the map will be the ListenerId and the value for that key is a Pair that represents the handler and
     * any listenerData that was passed at time of listener registration.
     *
     * @param string $event
     * @return Map<ListenerId, Pair<callable, array>>
     */
    public function listeners(string $event) : Map;

    /**
     * Returns the default PromiseCombinator that is to be used if an explicit PromiseCombinator is not passed to
     * emit().
     *
     * This SHOULD be PromiseCombinator::All() unless specifically overridden in calls to setDefaultPromiseCombinator.
     *
     * @return PromiseCombinator
     */
    public function getDefaultPromiseCombinator() : PromiseCombinator;

    /**
     * Overrides the default PromiseCombinator.
     *
     * @param PromiseCombinator $promiseCombinator
     */
    public function setDefaultPromiseCombinator(PromiseCombinator $promiseCombinator) : void;
}
