name: 'Unit Testing & Code Lint'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
      - name: PHPUnit
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          version: 10
          php_extensions: xdebug
      - name: Code Lint
        run: ./vendor/bin/labrador-cs src/ test/