name: 'Unit Testing & Code Lint'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHP 7.4 tests
        uses: php-actions/phpunit@v2
        with:
          version: 8
          php_version: 7.4

      - name: Run code sniffer
        run: composer run-script code-lint