name: 'Unit Testing & Code Lint'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v5
        with:
          php_version: 8.1
      - name: PHPUnit
        uses: php-actions/phpunit@v2
        with:
          version: 9
          php_version: 8.1
      - name: Code Lint
        run: composer run-script code-lint